<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Products</name>
   <tag></tag>
   <elementGuidId>0060bfec-db3f-4dc3-b270-5bf6fda63c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_17218400955395']/header/section[2]/div/div/nav/ul/li/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.header__nav--menu-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:text=&quot;Products&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f64e6efc-38c7-43c5-99b6-6cd8db908c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__nav--menu-title</value>
      <webElementGuid>e384be8b-eda1-41c5-a036-94e2241975ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>c66f7d94-1471-4da5-bcd9-2af75e790a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_17218400955395&quot;)/header[@class=&quot;header bg-white&quot;]/section[@class=&quot;header__nav--main-wrapper&quot;]/div[@class=&quot;header__nav--main bg-white&quot;]/div[@class=&quot;header__nav--wrapper main-wrapper&quot;]/nav[@class=&quot;header__nav&quot;]/ul[@class=&quot;header__nav--list&quot;]/li[@class=&quot;header__nav--item have-child-menu&quot;]/div[@class=&quot;header__nav--menu-title&quot;]</value>
      <webElementGuid>7b3b8dd2-8a46-4a19-87b2-d282653353fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_17218400955395']/header/section[2]/div/div/nav/ul/li/div</value>
      <webElementGuid>386bbc6d-b817-4ff4-9ced-9087ac321fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::div[3]</value>
      <webElementGuid>a7c56fd1-9138-41a4-b93b-9a7f71abfa7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::div[3]</value>
      <webElementGuid>82438e5d-c5b5-4b37-90b0-4d4d6ed5ccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Studio'])[1]/preceding::div[1]</value>
      <webElementGuid>879a7c48-762b-4019-a8c0-8c8e8d6d3668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::div[3]</value>
      <webElementGuid>21e67ca0-5d29-4141-9e09-50c229801c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Products']/parent::*</value>
      <webElementGuid>76665e90-2cc2-48f9-93c8-a9c2cfd02455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>cda499a1-43a8-44cf-a5cb-7d3c902ca475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>f18ace9e-dfec-4729-93d7-a8be668c2ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
