<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bad_AddProductReview.Rating</name>
   <tag></tag>
   <elementGuidId>537fe56b-9b6f-4703-8f48-2fb6c3dcc15d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addproductrating_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addproductrating_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#addproductrating_5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b3082ce-4e74-41db-b1f0-974bc0407466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>69fd0910-0c47-4f5d-af65-87601fdaf3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addproductrating_5</value>
      <webElementGuid>fd492d0b-163f-428c-9b7e-9aab06653312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.Rating</value>
      <webElementGuid>aee1f10e-bd29-4422-99b2-18b3496f635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e5fea2ac-a979-4932-8cf4-7dcb59fb15b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8411b9c4-4f60-47e0-87ce-db26d6e1f5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addproductrating_5&quot;)</value>
      <webElementGuid>2683944a-352a-445e-91da-230e0b35ec66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addproductrating_5']</value>
      <webElementGuid>0a39e546-ca06-4b7b-88b7-66a05335ca05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/form/div[2]/div[3]/ul/li[2]/input[5]</value>
      <webElementGuid>aba29a1f-2a68-4774-863f-cae8274c3a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>07fe176a-b4ef-4fa0-ab8e-bae8537b1afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'addproductrating_5' and @name = 'AddProductReview.Rating' and @type = 'radio']</value>
      <webElementGuid>9f572b55-d5ee-4417-bec7-5b2af385a809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
