<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Excellent_add-review</name>
   <tag></tag>
   <elementGuidId>e688d14d-bae8-4f5d-b119-c88340c14c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='add-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;add-review&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit review&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a55ef1-0469-418c-952c-0eb05f3eec9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>beb67a21-868a-44c7-93d4-c80ff7acff30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-review</value>
      <webElementGuid>b00ded5f-ca9f-4fc0-98b5-5b9c170972b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 write-product-review-button</value>
      <webElementGuid>f72f7585-55be-46bf-90ae-31066b484577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit review</value>
      <webElementGuid>a0c0a552-62a0-46f4-88bc-7b513421e2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-form&quot;)/form[1]/div[@class=&quot;buttons&quot;]/input[@class=&quot;button-1 write-product-review-button&quot;]</value>
      <webElementGuid>3c9d7ef7-7a1c-4cf5-ab82-f4733cbf52b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='add-review']</value>
      <webElementGuid>03ac6012-ad94-42cd-ac97-6dbb68731246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/form/div[3]/input</value>
      <webElementGuid>aff54481-26c6-45e6-b959-dd86d3b9e0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3e441688-a8e2-497b-ae34-59f02a36a2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'add-review']</value>
      <webElementGuid>0ab72ae7-822e-497c-85f3-93d05fe12d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
