<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Review text_AddProductReview.ReviewText</name>
   <tag></tag>
   <elementGuidId>240a8264-7739-42bc-9a2c-c9e495981c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='AddProductReview_ReviewText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AddProductReview_ReviewText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Review text:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f23d5cfd-c797-4dd7-9713-ab10323d575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>review-text</value>
      <webElementGuid>bdbc08c3-88bb-4cb5-b394-fc62625be62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4f139c8e-428d-4961-b269-eea0b0452540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddProductReview_ReviewText</value>
      <webElementGuid>02a4ae31-61f5-4309-a9f1-ca02eed3a82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.ReviewText</value>
      <webElementGuid>15d6608f-fb4b-4874-9fb7-d29d45c6dadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1b43cd8e-09f5-488a-af5d-1a31dbe019b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddProductReview_ReviewText&quot;)</value>
      <webElementGuid>6a86d7e6-9ee4-4df1-abc2-790a9e2ca2c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='AddProductReview_ReviewText']</value>
      <webElementGuid>05f05eef-8781-4861-8f42-9871f0edf7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/form/div[2]/div[2]/textarea</value>
      <webElementGuid>8b67948d-9f72-4fd3-a9d7-cf10ef228158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>04fcee30-9314-4eb0-9326-d9bf7942027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'AddProductReview_ReviewText' and @name = 'AddProductReview.ReviewText']</value>
      <webElementGuid>28b6751f-52c8-4782-b768-4c1a3eed7aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
