<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Compare products_button-2 remove-button</name>
   <tag></tag>
   <elementGuidId>ce1f87e1-0078-4b62-a50f-a3055495b758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Remove']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.button-2.remove-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Remove&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>127232f5-655d-4ec9-977e-2e9c1499de8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45b1069f-c308-4b5a-ba83-2c19e3d2baad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>b9bb1970-8ae6-46d0-9dd9-f8020b980871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>d958fd0b-5b6b-4c9b-bb96-3bc51686ffa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-2 remove-button</value>
      <webElementGuid>8c655694-4b3c-4087-948b-c8a68a00a75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setLocation('/compareproducts/remove/36')</value>
      <webElementGuid>35511ff4-ceb6-45b4-8ec9-aa38e0889149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-wrapper-main&quot;]/div[@class=&quot;center-2&quot;]/div[@class=&quot;page compare-products-page&quot;]/div[@class=&quot;page-body&quot;]/table[@class=&quot;compare-products-table&quot;]/tbody[1]/tr[@class=&quot;overview&quot;]/td[@class=&quot;a-center&quot;]/div[1]/p[@class=&quot;a-center&quot;]/input[@class=&quot;button-2 remove-button&quot;]</value>
      <webElementGuid>df84a1eb-5051-4f88-9d30-ff47efcbaefd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Remove']</value>
      <webElementGuid>d08f6d97-6c9f-44b9-adfc-08b4016ab6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>f8c02cfc-ec89-48dc-9613-708092ffee17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'Remove']</value>
      <webElementGuid>b93992a8-acb6-407c-9755-bba7bc9a514e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
